apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: 1.8.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: envoy-gateway-system
  releaseName: envoy-gateway
  values:
    crds:
      envoyGateway:
        enabled: true
      gatewayAPI:
        enabled: true
        channel: experimental
        safeUpgradePolicy:
          enabled: false
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
