---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: telegram-bot
  namespace: flux-system
spec:
  type: telegram
  address: https://api.telegram.org
  channel: "39918053"
  secretRef:
    name: telegram-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: telegram-default
  namespace: flux-system
spec:
  summary: ""
  providerRef:
    name: telegram-bot
  eventSources:
    - kind: HelmRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'