apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: /tailscale/client-id
    - secretKey: client_secret
      remoteRef:
        key: /tailscale/client-secret
