apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: '1.90.8' 
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 5m
  releaseName: tailscale-operator
  values:
    oauth:
      secret:
        name: tailscale-oauth
        clientIdKey: client_id
        clientSecretKey: client_secret
    operatorConfig:
      hostname: "tailscale-operator"
