apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linstor-affinity-controller
  namespace: piraeus-datastore
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: linstor-affinity-controller
      version: '1.5.0'
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
      interval: 5m
  releaseName: linstor-affinity-controller