apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: talos-loader-override
  namespace: piraeus-datastore
spec:
  storagePools:
    - name: ssd_pool
      lvmThinPool:
        thinPool: thin
        volumeGroup: linstor_ssd_lvm_pool
      properties:
        - name: StorDriver/LvcreateOptions
          value: --chunksize 1M --stripes 2 --stripesize 256k
      source:
        hostDevices:
          - /dev/sda
          - /dev/sdb
  nodeSelector:
    local-disk/storage: "yes"
  podTemplate:
    spec:
      initContainers:
        - name: drbd-shutdown-guard
          $patch: delete
        - name: drbd-module-loader
          $patch: delete
      volumes:
        - name: run-systemd-system
          $patch: delete
        - name: run-drbd-shutdown-guard
          $patch: delete
        - name: systemd-bus-socket
          $patch: delete
        - name: lib-modules
          $patch: delete
        - name: usr-src
          $patch: delete
        - name: etc-lvm-backup
          hostPath:
            path: /var/etc/lvm/backup
            type: DirectoryOrCreate
        - name: etc-lvm-archive
          hostPath:
            path: /var/etc/lvm/archive
            type: DirectoryOrCreate
