apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstor-cluster
spec:
  properties:
    - name: DrbdOptions/Net/ping-timeout
      value: "30"
    - name: DrbdOptions/Net/connect-int
      value: "10"
    - name: DrbdOptions/Net/max-buffers
      value: "36864"
    - name: DrbdOptions/Net/rcvbuf-size
      value: "10485760"
    - name: DrbdOptions/Net/sndbuf-size
      value: "10485760"
    - name: DrbdOptions/PeerDevice/c-fill-target
      value: "2048"
    - name: DrbdOptions/PeerDevice/c-plan-ahead
      value: "10"
    - name: DrbdOptions/PeerDevice/resync-rate
      value: "245760"
    - name: DrbdOptions/PeerDevice/c-max-rate
      value: "737280"
    - name: DrbdOptions/PeerDevice/c-min-rate
      value: "245760"
  controller:
    podTemplate:
      spec:
        containers:
        - name: linstor-controller
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
  csiController:
    podTemplate:
      spec:
        containers:
        - name: csi-provisioner
          env:
          - name: TIMEOUT
            value: "10m"
        - name: csi-snapshotter
          env:
          - name: TIMEOUT
            value: "10m"
        - name: csi-attacher
          env:
          - name: TIMEOUT
            value: "10m"
