apiVersion: piraeus.io/v1
kind: LinstorNodeConnection
metadata:
  name: dedicated-storage-10g
spec:
  paths:
    - name: 10g-data
      interface: storage
    - name: 1g-control
      interface: default-ipv4
  properties:
    - name: "Paths/10g-data/DrbdOptions/Net/use-rlink-checksums"
      value: "no" 