apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstor-cluster
spec:
  properties:
    - name: DrbdOptions/Net/ping-timeout
      value: "30"
    - name: DrbdOptions/Net/connect-int
      value: "10"
  controller:
    podTemplate:
      spec:
        containers:
        - name: linstor-controller
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
  csiController:
    podTemplate:
      spec:
        containers:
        - name: csi-provisioner
          env:
          - name: TIMEOUT
            value: "10m"
        - name: csi-snapshotter
          env:
          - name: TIMEOUT
            value: "10m"
        - name: csi-attacher
          env:
          - name: TIMEOUT
            value: "10m"
