apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: piraeus-charts
  namespace: piraeus-datastore
spec:
  interval: 24h
  url: https://piraeus.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: piraeus-datastore
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: snapshot-controller
      version: '4.*'
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
      interval: 5m
  releaseName: snapshot-controller