apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-single
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: linstor.csi.linbit.com
parameters:
  DrbdOptions/Disk/disk-flushes: 'no'
  DrbdOptions/Disk/md-flushes: 'no'
  DrbdOptions/Net/max-buffers: '10000'
  csi.storage.k8s.io/fstype: ext4
  linstor.csi.linbit.com/autoPlace: '1'
  linstor.csi.linbit.com/storagePool: ssd_pool
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-replica
provisioner: linstor.csi.linbit.com
parameters:
  DrbdOptions/Disk/disk-flushes: 'no'
  DrbdOptions/Disk/md-flushes: 'no'
  DrbdOptions/Net/max-buffers: '10000'
  csi.storage.k8s.io/fstype: ext4
  linstor.csi.linbit.com/autoPlace: '3'
  linstor.csi.linbit.com/storagePool: ssd_pool
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: single
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: linstor.csi.linbit.com
parameters:
  DrbdOptions/Disk/disk-flushes: 'no'
  DrbdOptions/Disk/md-flushes: 'no'
  DrbdOptions/Net/max-buffers: '10000'
  csi.storage.k8s.io/fstype: ext4
  linstor.csi.linbit.com/autoPlace: '1'
  linstor.csi.linbit.com/storagePool: nvme_pool
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: replica
provisioner: linstor.csi.linbit.com
parameters:
  DrbdOptions/Disk/disk-flushes: 'no'
  DrbdOptions/Disk/md-flushes: 'no'
  DrbdOptions/Net/max-buffers: '10000'
  csi.storage.k8s.io/fstype: ext4
  linstor.csi.linbit.com/autoPlace: '3'
  linstor.csi.linbit.com/storagePool: nvme_pool
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer