apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: spegel
  namespace: spegel
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/spegel-org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 1m
  chart:
    spec:
      chart: spegel
      interval: 5m
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: spegel
  values:
    grafanaDashboard:
      enabled: true
    serviceMonitor:
      enabled: true
    spegel:
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts