apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-tunnel
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  replicas: 3
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      imagePullSecrets:
        - name: cappyt
      containers:
      - name: cf-tunnel
        image: git.cappyt.sh/cappyt/cloudflared:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: NO_AUTOUPDATE
            value: "true"
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: cloudflared-token
          - name: CLOUDFLARED_QUIC_INITIAL_PACKET_SIZE
            value: "1230"
        args:
          - "tunnel"
          - "--protocol"
          - "http2"
          - "--loglevel"
          - "debug"
          - "run"
        resources:
          limits:
            memory: "30Mi"
            cpu: "50m"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflared-token
  data:
    - secretKey: token
      remoteRef:
        key: /default/cloudflare/cloudflared-token