apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: couchdb
  namespace: default
spec:
  interval: 24h
  url: https://apache.github.io/couchdb-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: couchdb-obsidian
  namespace: default
spec:
  interval: 10m
  timeout: 20m
  chart:
    spec:
      chart: couchdb
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: couchdb
        namespace: default
  values:
    couchdbConfig:
      couchdb:
        uuid: 6235c411-dcba-4097-a360-356bd5943b14
      chttpd:
        require_valid_user: true
    adminUsername: cappyt
    persistentVolume:
      enabled: true
      size: 10Gi
      storageClass: single
