apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: couchdb
  namespace: default
spec:
  interval: 24h
  url: https://apache.github.io/couchdb-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: couchdb-obsidian
  namespace: default
spec:
  interval: 10m
  timeout: 20m
  chart:
    spec:
      chart: couchdb
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: couchdb
        namespace: default
