apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  namespace: default
spec:
  selector:
    matchLabels:
      app: gitea
  serviceName: gitea
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-gitea
      containers:
      - name: gitea
        image: gitea/gitea:1.25.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: private-pool
spec:
  type: LoadBalancer
  selector:
    app: gitea
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 22
    targetPort: ssh
    name: ssh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitea
  namespace: default
spec:
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: replica
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gitea-route
  namespace: default
spec:
  hostnames:
    - git.cappyt.sh
  parentRefs:
  - name: public-gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - name: gitea
      port: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: immich-dns
  namespace: default
spec:
  endpoints:
  - dnsName: git.cappyt.sh
    recordTTL: 180
    recordType: A
    targets:
    - 185.242.182.145
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"