apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
  namespace: default
spec:
  selector:
    matchLabels:
      app: gitea
  serviceName: gitea
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-gitea
      containers:
      - name: gitea
        image: gitea/gitea:1.24.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: default
  annotations:
    metallb.universe.tf/address-pool: private-pool
spec:
  type: LoadBalancer
  selector:
    app: gitea
  ports:
  - port: 80
    targetPort: http
    name: http
  - port: 22
    targetPort: ssh
    name: ssh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitea
  namespace: default
spec:
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-single
