apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jitsi
  namespace: default
spec:
  interval: 24h
  url: https://jitsi-contrib.github.io/jitsi-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jitsi
  namespace: default
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: jitsi-meet
      version: '1.5.2'
      sourceRef:
        kind: HelmRepository
        name: jitsi
      interval: 5m
  releaseName: jitsi
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    publicURL: "meet.cappyt.sh"
    tz: "Europe/Rome"
    websockets:
      colibri:
        enabled: true
      xmpp:
        enabled: false
    jvb:
      service:
        type: NodePort
      
      nodePort: 30144

      publicIPs:
        - 185.242.183.144