apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: linkwarden-secrets
  data:
    - secretKey: meili_master_key
      remoteRef:
        key: /default/linkwarden/meili_master_key
    - secretKey: nextauth_secret
      remoteRef:
        key: /default/linkwarden/nextauth_secret
    - secretKey: oidc-id
      remoteRef:
        key: /default/linkwarden/oidc-id
    - secretKey: oidc-secret
      remoteRef:
        key: /default/linkwarden/oidc-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-cluster
  namespace: default
spec:
  imagePullPolicy: Always
  instances: 3
  storage:
    size: 5Gi
    storageClass: single
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: true
  backup:
    target: prefer-standby
    volumeSnapshot:
      online: true
      snapshotOwnerReference: none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden-meilisearch
  namespace: default
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: linkwarden-meilisearch
  template:
    metadata:
      labels:
        app: linkwarden-meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.12.8
          imagePullPolicy: IfNotPresent
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: linkwarden-secrets
                  key: meili_master_key
            - name: MEILI_NO_ANALYTICS
              value: "true"
          ports:
            - containerPort: 7700
              name: http
          volumeMounts:
            - name: data
              mountPath: /meili_data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-linkwarden-meilisearch
---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden-meilisearch
  namespace: default
spec:
  selector:
    app: linkwarden-meilisearch
  ports:
    - port: 7700
      targetPort: 7700
      name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-linkwarden-meilisearch
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: replica
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: linkwarden
  template:
    metadata:
      labels:
        app: linkwarden
    spec:
      containers:
        - name: linkwarden
          image: ghcr.io/linkwarden/linkwarden:latest
          imagePullPolicy: Always
          env:
            - name: MEILISEARCH_HOST
              value: http://linkwarden-meilisearch:7700
            - name: MEILISEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: linkwarden-secrets
                  key: meili_master_key
            - name: NEXTAUTH_URL
              value: https://bookmarks.cappyt.sh/api/v1/auth
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: linkwarden-secrets
                  key: nextauth_secret
            # Database Configuration using CNPG Secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: linkwarden-cluster-app
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: linkwarden-cluster-app
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: linkwarden-cluster-app
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: linkwarden-cluster-app
                  key: dbname
            - name: DATABASE_URL
              value: postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/$(DB_NAME)
            - name: NEXT_PUBLIC_OLLAMA_ENDPOINT_URL
              value: "http://192.168.5.68:11434"
            - name: OLLAMA_MODEL
              value: phi4-mini:latest
            - name: NEXT_PUBLIC_DISABLE_REGISTRATION
              value: "true"
            - name: NEXT_PUBLIC_AUTHENTIK_ENABLED
              value: "true"
            - name: AUTHENTIK_CUSTOM_NAME
              value: "Cappy's"
            - name: AUTHENTIK_ISSUER
              value: https://auth.cappyt.sh/webman/sso
            - name: AUTHENTIK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: linkwarden-secrets
                  key: oidc-id
            - name: AUTHENTIK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: linkwarden-secrets
                  key: oidc-secret
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - name: data
              mountPath: /data/data
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-linkwarden
---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden
  namespace: default
spec:
  selector:
    app: linkwarden
  ports:
    - port: 3000
      targetPort: 3000
      name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-linkwarden
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: replica
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkwarden-route
  namespace: default
spec:
  hostnames:
    - bookmarks.cappyt.sh
  parentRefs:
    - name: public-gateway
      namespace: kube-system
  rules:
    - backendRefs:
        - name: linkwarden
          port: 3000
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: linkwarden-dns
  namespace: default
spec:
  endpoints:
    - dnsName: bookmarks.cappyt.sh
      recordTTL: 180
      recordType: A
      targets:
        - 185.242.182.145
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "false"
