apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-rcon
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: minecraft-rcon
  data:
    - secretKey: rcon-pass
      remoteRef:
        key: /default/minecraft/rcon-pass
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-cf-api
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: minecraft-cf-api
  data:
    - secretKey: token
      remoteRef:
        key: /default/minecraft/curseforge-api-key