---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy-deployment
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: ntfy 
          image: binwiederhier/ntfy:v2.16.0
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          args: ["serve"]
          env:
            - name: TZ
              value: Europe/Rome
            - name: NTFY_DEBUG
              value: "false"
            - name: NTFY_LOG_LEVEL
              value: INFO
            - name: NTFY_BASE_URL
              value: https://ntfy.cappyt.sh
            - name: NTFY_ATTACHMENT_CACHE_DIR
              value: /var/lib/ntfy/attachments
            - name: NTFY_CACHE_FILE
              value: /var/lib/ntfy/cache.db
            - name: NTFY_AUTH_FILE
              value: /var/lib/ntfy/auth.db
            - name: NTFY_AUTH_DEFAULT_ACCESS
              value: deny-all
            - name: NTFY_BEHIND_PROXY
              value: "true"
            - name: NTFY_ENABLE_LOGIN
              value: "true"
            - name: NTFY_ENABLE_SIGNUP
              value: "false"
            - name: NTFY_VISITOR_REQUEST_LIMIT_BURST
              value: "60"
            - name: NTFY_VISITOR_REQUEST_LIMIT_REPLENISH
              value: "1s"
            - name: NTFY_VISITOR_EMAIL_LIMIT_BURST
              value: "0"
            - name: NTFY_VISITOR_EMAIL_LIMIT_REPLENISH
              value: "1h"
            - name: NTFY_VISITOR_ATTACHMENT_SIZE_LIMIT
              value: "512k"
            - name: NTFY_VISITOR_ATTACHMENT_TOTAL_SIZE_LIMIT
              value: "10M"
            - name: NTFY_LISTEN_HTTP
              value: ":8080"
            - name: NTFY_CACHE_STARTUP_QUERIES
              value: |
                pragma journal_mode = WAL;
                pragma synchronous = normal;
                pragma temp_store = memory;
                pragma busy_timeout = 15000;
                vacuum;
          ports: 
            - containerPort: 8080
              name: http-ntfy
          resources:
            limits:
              memory: 300Mi
              cpu:  200m
            requests:
              cpu: 150m
              memory: 150Mi
          volumeMounts:
              - mountPath: /var/lib/ntfy
                name: cache-volume
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: ntfy-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: replica
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: default
spec:
  selector:
    app: ntfy
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ntfy-route
  namespace: default
spec:
  hostnames:
    - ntfy.cappyt.sh
  parentRefs:
  - name: public-gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - name: ntfy
      port: 8080
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ntfy-dns
  namespace: default
spec:
  endpoints:
  - dnsName: ntfy.cappyt.sh
    recordTTL: 180
    recordType: A
    targets:
    - 185.242.182.145
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"