apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
  namespace: default
spec:
  selector:
    matchLabels:
      app: outline
  template:        
    metadata:
      labels:
        app: outline
    spec:
      volumes:
        - name: outline-data
          persistentVolumeClaim:
            claimName: data-outline
      containers:
      - name: outline
        image: outlinewiki/outline:1.0.1
        env:
          - name: NODE_ENV
            value: production
          - name: URL
            value: https://wiki.cappyt.sh
          - name: DEFAULT_LANGUAGE
            value: en_US
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: secret-key
                name: outline-secrets
          - name: UTILS_SECRET
            valueFrom:
              secretKeyRef:
                key: utils-secret
                name: outline-secrets
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: uri
                name: outline-cluster-app
          - name: REDIS_URL
            value: redis://outline-dragonfly:6379
          - name: OIDC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: oidc-client-id
                name: outline-secrets
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: oidc-client-secret
                name: outline-secrets
          - name: OIDC_ISSUER_URL
            value: https://auth.cappyt.sh/webman/sso
          - name: OIDC_DISPLAY_NAME
            value: Cappys
          - name: OIDC_SCOPES
            value: "openid email"
          - name: SMTP_HOST
            value: mail.smtp2go.com
          - name: SMTP_PORT
            value: "465"
          - name: SMTP_SECURE
            value: "true"
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                key: smtp-username
                name: outline-secrets
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: smtp-password
                name: outline-secrets
          - name: SMTP_FROM_EMAIL
            value: "Outline <noreply@cappyt.sh>"
          - name: ENABLE_UPDATES
            value: "false"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: 128Mi
            cpu: "100m"
        volumeMounts:
          - mountPath: /var/lib/outline/data
            name: outline-data
        ports:
        - containerPort: 3000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: outline
  namespace: default
spec:
  selector:
    app: outline
  ports:
  - port: 8080
    targetPort: http
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: outline-route
  namespace: default
spec:
  hostnames:
    - wiki.cappyt.sh
  parentRefs:
  - name: public-gateway
    namespace: kube-system
  rules:
  - backendRefs:
    - name: outline
      port: 8080
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: outline-dns
  namespace: default
spec:
  endpoints:
  - dnsName: wiki.cappyt.sh
    recordTTL: 180
    recordType: A
    targets:
    - 185.242.182.145
    providerSpecific:
      - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
        value: "false"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: outline-secrets
  data:
    - secretKey: secret-key
      remoteRef:
        key: /default/outline/secret-key
    - secretKey: utils-secret
      remoteRef:
        key: /default/outline/utils-secret
    - secretKey: oidc-client-id
      remoteRef:
        key: /default/outline/oidc-client-id
    - secretKey: oidc-client-secret
      remoteRef:
        key: /default/outline/oidc-client-secret
    - secretKey: smtp-username
      remoteRef:
        key: /default/outline/smtp-username
    - secretKey: smtp-password
      remoteRef:
        key: /default/outline/smtp-password
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: outline-dragonfly
  namespace: default
spec:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 750Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-outline
  namespace: default
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: replica
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: outline-cluster
  namespace: default
spec:
  imagePullPolicy: Always
  instances: 3
  storage:
    size: 15Gi
    storageClass: single
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: true
  backup:
    target: prefer-standby
    volumeSnapshot:
      online: true
      snapshotOwnerReference: none