apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: minio-system
spec:
  interval: 24h
  url: https://operator.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: operator
      version: '7.1.1'
      sourceRef:
        kind: HelmRepository
        name: minio-operator
      interval: 5m
  releaseName: minio-operator
