apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: tenant
      version: '7.1.1'
      sourceRef:
        kind: HelmRepository
        name: minio-operator
      interval: 5m
  releaseName: minio-tenant
  values:
    tenant:
      name: minio
      pools:
        - name: pool-0
          servers: 3
          volumesPerServer: 1
          size: 30Gi
          storageClassName: local-single
          