apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-kube-prometheus-alertmanager
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: alertmanager-kube-prometheus-alertmanager
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          
          route:
            group_by: ['alertname']
            group_wait: 0s
            group_interval: 1m
            repeat_interval: 2m
            receiver: 'null'
            routes:
              - match:
                  alertname: Watchdog
                receiver: 'healthchecks_io'
                group_wait: 0s
                repeat_interval: 2m
              
              # - match:
              #     severity: critical
              #   receiver: 'telegram'

          receivers:
            - name: 'null'
            - name: 'healthchecks_io'
              webhook_configs:
                - url: '{{ .HEALTHCHECKS_URL }}'
                  send_resolved: false
            
            # - name: 'telegram'
            #   telegram_configs:
            #     - bot_token: '{{ .TELEGRAM_TOKEN }}'
            #       chat_id: {{ .TELEGRAM_CHAT_ID }}

  data:
    - secretKey: HEALTHCHECKS_URL
      remoteRef:
        key: /monitoring/alertmanager/healthchecks-url
    # - secretKey: TELEGRAM_TOKEN
    #   remoteRef:
    #     key: /monitoring/alertmanager/telegram-token
