apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: grafana-oidc-secrets
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: /monitoring/grafana/oidc-id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /monitoring/grafana/oidc-secret
