apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- grafana-secrets.yaml
- prometheus.yaml
- custom-dashboards.yaml
- mkt-exporter.yaml
- zte-exporter.yaml
- loki.yaml
- alloy.yaml
- smartctl-exporter.yaml
