apiVersion: v1
kind: ConfigMap
metadata:
  name: mkt-logs-alloy
  namespace: monitoring
data:
  config.alloy: |
    // 1. Define the final destination for logs (your Loki instance)
    loki.write "loki_output" {
      endpoint {
        url = "http://loki-headless.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      }
    }

    loki.relabel "relabeler" {
      rule {
        source_labels = ["__syslog_message_hostname"]
        target_label  = "routerboard"
      }

      rule {
        source_labels = ["__syslog_connection_hostname"]
        target_label  = "syslog_host"
      }

      forward_to = [loki.write.loki_output.receiver]
    }
 
    loki.source.syslog "local" {
      listener {
        address  = "0.0.0.0:1514"
        labels   = { component = "loki.source.syslog", protocol = "tcp" }
      }

      forward_to = [loki.relabel.relabeler.receiver]
    }
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mkt-logs-alloy
  namespace: monitoring
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: alloy
      version: '1.4.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  releaseName: mkt-logs-alloy
  values:
    crds:
      create: false
    rbac:
      create: false
    serviceAccount:
      create: false
    alloy:
      configMap:
        create: false
        name: mkt-logs-alloy
        key: config.alloy
      extraPorts:
        - name: "syslog-tcp"
          port: 1514
          targetPort: 1514
          protocol: "TCP"
    serviceMonitor:
      enabled: false
    controller:
      type: deployment
    service:
      enabled: false
---
apiVersion: v1
kind: Service
metadata:
  name: mkt-logs-alloy
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: mkt-logs-alloy
  ports:
  - name: syslog-tcp
    port: 31514
    targetPort: syslog-tcp
    protocol: TCP
