apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
  namespace: monitoring
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: '0.15.4'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 5m
  releaseName: smartctl-exporter
  values:
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: false