apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  imagePullPolicy: IfNotPresent
  config:
    scratchSpaceStorageClass: single
    featureGates:
      - HonorWaitForFirstConsumer
  infra:
    nodeSelector:
      kubernetes.io/os: linux
  workload:
    nodeSelector:
      node-type: nvme
