apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubevirt-manager-oidc
  namespace: kubevirt-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: kubevirt-manager-oidc
    creationPolicy: Owner
  data:
    - secretKey: OAUTH2_PROXY_CLIENT_ID
      remoteRef:
        key: /kubevirt/oauth-client-id
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: /kubevirt/oauth-client-secret
    - secretKey: OAUTH2_PROXY_COOKIE_SECRET
      remoteRef:
        key: /kubevirt/cookie-secret
