---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: public-services
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels:
          type: public