apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cilium
      version: '1.18.1'
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 5m
  releaseName: cilium
  values:
    extraConfig:
      devices: enp89s0.95
    bpf:
      masquerade: true
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    cluster:
      name: personal-omni-personal
    dashboards:
      enabled: true
    gatewayAPI:
      enableAlpn: true
      enableAppProtocol: true
      enabled: true
    hubble:
      enabled: false
      relay:
        enabled: false
      ui:
        enabled: false
    ipam:
      mode: kubernetes
    k8sServiceHost: localhost
    k8sServicePort: 7445
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      replicas: 2
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    routingMode: tunnel
    securityContext:
      capabilities:
        ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETGID
        - SETUID
        cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
    tunnelProtocol: vxlan
