apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-talos-csi
  namespace: synology-csi
spec:
  interval: 24h
  url: https://zebernst.github.io/synology-csi-talos
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: synology-csi
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: synology-talos-csi
      interval: 5m
  releaseName: synology-csi
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    clientInfoSecret:
      create: false
      name: client-info-secret
    storageClasses:
      block:
        disabled: false
        isDefault: true
        parameters:
          dsm: '192.168.5.10'
          location: '/volume1'
          protocol: iscsi
          csi.storage.k8s.io/fstype: ext4
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
      block-retain:
        disabled: false
        isDefault: true
        parameters:
          dsm: '192.168.5.10'
          location: '/volume1'
          protocol: iscsi
          csi.storage.k8s.io/fstype: ext4
        reclaimPolicy: Retain
        volumeBindingMode: Immediate