apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: piraeus-charts
  namespace: synology-csi
spec:
  interval: 5m0s
  url: https://piraeus.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapshot-controller
  namespace: synology-csi
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: snapshot-controller
      version: '8.*'
      sourceRef:
        kind: HelmRepository
        name: piraeus-charts
      interval: 5m
  releaseName: snapshot-controller
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true