apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 24h
  url: https://backube.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 5m
  releaseName: metallb
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    frr:
      enabled: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ippool
  namespace: metallb-system
spec:
  dependsOn:
    - name: metallb
  interval: 5m
  path: "./clusters/personal/metallb"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system