apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: '0.26.1'
      sourceRef:
        kind: HelmRepository
        name: cnpg
      interval: 5m
  releaseName: cnpg
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    monitoring:
      podMonitorEnabled: true
    webhook:
      mutating:
        failurePolicy: Ignore
      validating:
        failurePolicy: Ignore