---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: element-synapse-secrets
  namespace: element-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: element-synapse-secrets
    creationPolicy: Owner
  data:
  - secretKey: signingKey
    remoteRef:
      key: /element/synapse/signing-key
  - secretKey: registrationSharedSecret
    remoteRef:
      key: /element/synapse/registration-shared-secret
  - secretKey: macaroon
    remoteRef:
      key: /element/synapse/macaroon-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: element-mas-secrets
  namespace: element-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: element-mas-secrets
    creationPolicy: Owner
  data:
  - secretKey: encryption
    remoteRef:
      key: /element/mas/encryption-secret
  - secretKey: synapseSharedSecret
    remoteRef:
      key: /element/mas/synapse-shared-secret
  - secretKey: rsa
    remoteRef:
      key: /element/mas/private-keys/rsa
  - secretKey: ecdsaPrime256v1
    remoteRef:
      key: /element/mas/private-keys/ecdsa-prime256v1
  - secretKey: ecdsaSecp256k1
    remoteRef:
      key: /element/mas/private-keys/ecdsa-secp256k1
  - secretKey: ecdsaSecp384r1
    remoteRef:
      key: /element/mas/private-keys/ecdsa-secp384r1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: element-livekit-secrets
  namespace: element-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: element-livekit-secrets
    creationPolicy: Owner
  data:
  - secretKey: keys
    remoteRef:
      key: /element/livekit/keys-yaml
  - secretKey: secret
    remoteRef:
      key: /element/livekit/secret
