apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- bridges.yaml
- helmrepository.yaml
- cnpg-cluster.yaml
- helmrelease.yaml
- httproute.yaml
- dns.yaml
- secrets.yaml