apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://secrets.cappyt.sh
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: external-secrets
            name: infisical-token-global
          clientSecret:
            key: clientSecret
            namespace: external-secrets
            name: infisical-token-global
      secretsScope:
        projectSlug: personal-k8s
        environmentSlug: prod
        secretsPath: /
        recursive: false
        expandSecretReferences: false
