
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 24h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/dragonflydb/dragonfly-operator/helm/dragonfly-operator
  ref:
    tag: v1.3.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly-operator
  namespace: dragonfly-operator-system
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: dragonfly-operator
    namespace: dragonfly-operator-system
  releaseName: dragonfly-operator
  values:
    serviceMonitor:
      enabled: true
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: dragonfly-operator
              namespace: dragonfly-operator-system
            patch: |
              - op: replace
                path: /spec/template/spec/containers/1/args
                value: ['--health-probe-bind-address=:8081', '--metrics-bind-address=0.0.0.0:8080', '--leader-elect']
