apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: suse-edge
  namespace: flux-system
spec:
  interval: 1h
  url: https://suse-edge.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cdi
  namespace: cdi
spec:
  interval: 5m
  chart:
    spec:
      chart: cdi
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: suse-edge
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
