apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    podResourceRequirements:
      limits:
        cpu: 750m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 60M
    scratchSpaceStorageClass: single