apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-minio-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: velero-minio-credentials
    creationPolicy: Owner
  data:
  - secretKey: cloud
    remoteRef:
      key: /velero/minio
      decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-ui-auth
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: velero-ui-auth
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: /velero/ui/auth
      property: username
  - secretKey: password
    remoteRef:
      key: /velero/ui/auth
      property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-ui-oauth
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: velero-ui-oauth
    creationPolicy: Owner
  data:
  - secretKey: oauth-client-id
    remoteRef:
      key: /velero/ui/oauth-client-id
  - secretKey: oauth-client-secret
    remoteRef:
      key: /velero/ui/oauth-client-secret