apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-minio-credentials
  namespace: velero
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: cluster-secret-store
    kind: SecretStore
  target:
    name: velero-minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: cloud
      remoteRef:
        key: velero/minio
        decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-ui-auth
  namespace: velero
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: cluster-secret-store
    kind: SecretStore
  target:
    name: velero-ui-auth
    creationPolicy: Owner
   dataFrom:
    - extract:
        key: velero/ui/auth