apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: "11.3.2"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: velero
  values:
    image:
      repository: velero/velero
      tag: v1.17.2
    deployNodeAgent: true
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.13.2
        volumeMounts:
          - mountPath: /target
            name: plugins
    configuration:
      features: EnableCSI
      volumeSnapshotLocation:
        - name: default
          provider: aws
          config:
            region: brescia
    credentials:
      useSecret: true
      name: velero-minio-credentials
    upgradeCRDs: false