apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero-ui
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero-ui
      version: "0.14.0"
      sourceRef:
        kind: HelmRepository
        name: otwld
        namespace: velero
  values:
    # Velero namespace
    env:
      - name: VELERO_NAMESPACE
        value: velero
      - name: BASIC_AUTH_ENABLED
        value: "true"
      - name: BASIC_AUTH_USERNAME
        valueFrom:
          secretKeyRef:
            name: velero-ui-auth
            key: username
      - name: BASIC_AUTH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: velero-ui-auth
            key: password
      - name: OAUTH_AUTH_ENABLED
        value: "true"
      - name: OAUTH_NAME
        value: "Cappy's"
      - name: OAUTH_AUTHORIZATION_URL
        value: "https://auth.cappyt.sh/webman/sso/SSOOauth.cgi"
      - name: OAUTH_USER_INFO_URL
        value: "https://auth.cappyt.sh/webman/sso/SSOUserInfo.cgi"
      - name: OAUTH_TOKEN_URL
        value: "https://auth.cappyt.sh/webman/sso/SSOAccessToken.cgi"
      - name: OAUTH_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: velero-ui-oauth
            key: oauth-client-id
      - name: OAUTH_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: velero-ui-oauth
            key: oauth-client-secret
      - name: OAUTH_OAUTH_SCOPE
        value: "openid profile email"
      - name: OAUTH_REDIRECT_URI
        value: https://velero.cappyt.sh/login
      - name: OAUTH_GROUP_CLAIM
        value: groups
    # Service configuration
    service:
      type: ClusterIP
      port: 3000
    # Ingress or Gateway API will handle external access
    ingress:
      enabled: false
    # Resource limits
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    # Security context
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      tag: 0.10.1

