apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: velero-ui
  namespace: velero
spec:
  endpoints:
  - dnsName: velero.cappyt.sh
    recordTTL: 180
    recordType: A
    targets:
    - 185.242.182.145
    providerSpecific:
    - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
      value: "false"