apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: velero-ui
  namespace: velero
spec:
  parentRefs:
  - name: public-gateway
    namespace: kube-system
  hostnames:
  - velero.cappyt.sh
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: velero-ui
      port: 3000