apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stunner
  namespace: stunner-system
spec:
  interval: 24h
  url: https://l7mp.io/stunner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stunner
  namespace: stunner-system
spec:
  interval: 1m
  chart:
    spec:
      chart: stunner
      interval: 5m
      version: 0.21.0
      sourceRef:
        kind: HelmRepository
        name: stunner